version: '3.8'

services:
  web:
    build: .
    expose:
      - 8000
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=UpTraderTZ.settings
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume: