# Generated by Django 5.2.5 on 2025-08-14 07:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Имя меню')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Название пункта')),
                ('url', models.CharField(max_length=255, verbose_name='URL пункта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родитель')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
