# Generated by Django 5.2.5 on 2025-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='menu.menuitem', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Явный URL или named URL. Если пусто, используется автоматический иерархический URL.', max_length=255, verbose_name='URL пункта (опционально, для переопределения)'),
        ),
    ]
